version: '3.7'

services:

  db:
    image: mysql:8.0.17
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080